#!/usr/bin/env python3
"""Generate the index in docs/decisions/README.md from each ADR's own lines.

    python3 tools/adr-index.py           # rewrite the index between its markers
    python3 tools/adr-index.py --check   # exit 1 and say which rows differ

The index was hand-maintained, and twice reviewed against the files it points
at: on 2026-09-21 three of fourteen rows disagreed with their ADR, and on
2026-10-02 eleven rows omitted amendments their ADR's body carried (issue #10,
H4). Each row restated a fact its own target owns - rule 1 in CLAUDE.md broken
in the project's own index. So the row is now the target's words: the title is
the ADR's `# NNNN - Title` heading and the status is its `**Status:**`
paragraph (up to the first blank line), whitespace collapsed. An amendment is
listed in the index exactly when its ADR's status line names it, which is
where docs/decisions/README.md says it must be named.

check-staleness.py runs --check, so an ADR whose status line changed without
this tool being re-run is reported with the generated files.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR = os.path.join(ROOT, "docs", "decisions")
README = os.path.join(DIR, "README.md")
START = "<!-- adr-index: generated by tools/adr-index.py; do not edit by hand -->"
END = "<!-- adr-index: end -->"


def rows():
    out = []
    for name in sorted(os.listdir(DIR)):
        m = re.match(r"^(\d{4})-.*\.md$", name)
        if not m:
            continue
        lines = open(os.path.join(DIR, name), encoding="utf-8").read().splitlines()
        title = next((l for l in lines if l.startswith("# ")), "# ?")
        title = re.sub(r"^#\s+\d{4}\s*[—-]\s*", "", title).strip()
        status, on = [], False
        for l in lines:
            if not on and l.startswith("**Status:**"):
                on = True
            if on:
                if not l.strip():
                    break
                status.append(l.strip())
        st = " ".join(status)
        st = re.sub(r"^\*\*Status:\*\*\s*", "", st) or "(no `**Status:**` line)"
        st = st.replace("|", "\\|")
        out.append(f"| [{m.group(1)}]({name}) | {title} | {st} |")
    return out


def table():
    return "\n".join([START, "", "| # | Title | Status |", "|---|---|---|"]
                     + rows() + ["", END])


def main():
    text = open(README, encoding="utf-8").read()
    if START not in text or END not in text:
        print(f"adr-index: {os.path.relpath(README, ROOT)} has no index markers")
        return 1
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    new = head + table() + tail
    if "--check" in sys.argv:
        if new == text:
            return 0
        have = set(rest.split(END, 1)[0].splitlines())
        for r in rows():
            if r not in have:
                print(f"adr-index: docs/decisions/README.md index row differs "
                      f"from its ADR: {r[:90]}... - run tools/adr-index.py")
        print("adr-index: docs/decisions/README.md index is not what "
              "tools/adr-index.py generates - run it")
        return 1
    if new != text:
        open(README, "w", encoding="utf-8").write(new)
        print("adr-index: index rewritten")
    else:
        print("adr-index: index already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
