#!/usr/bin/env python3
"""
The instrument body's CAD pipeline: parameters in, renders and cut files out,
and a check that every output still matches the source it claims to show.

    python3 tools/cad.py params    # regenerate mechanical/cad/generated/params.scad
    python3 tools/cad.py build     # params, then every STALE output (--all: every output)
    python3 tools/cad.py build hero plan-top   # ...or just these, stale or not
    python3 tools/cad.py check     # exit 1 if anything is stale, missing or hand-edited
    python3 tools/cad.py explain hero          # which inputs moved, and since which commit

WHY THIS EXISTS. This repository's one failure is "a value changes and the
documents derived from it do not follow" (CLAUDE.md). A render is the most
derived document there is, and the least greppable: no staleness pattern can
read a PNG. So every output carries a FINGERPRINT - a hash over the git blob
ids of every file it was built from, found by walking include/use/import from
its source - and `check` recomputes it. A render made before its model moved
is reported by name, with the file that moved.

The fingerprint is also STAMPED INTO THE IMAGE, in a footer band, because the
reader looks at the picture and not at OUTPUTS.csv. A render pasted into a
chat, a review or a vendor email still says which CAD state it shows, and
`explain` turns the stamp back into commits.

WHAT IS GENERATED, and therefore must never be edited by hand - the same trap
as hardware/bom.csv:
    mechanical/cad/generated/params.scad   from config/key-layout.yaml + config/body.yaml
    mechanical/OUTPUTS.csv                 the fingerprint ledger
    every file named as `out` in mechanical/outputs.yaml

`check` never needs OpenSCAD - it only hashes - so it runs from the commit
gate (check-staleness.py) on any machine. `build` needs openscad (2021.01+),
xvfb-run when there is no display, Pillow for the stamp, and gmsh for the
STEP-to-mesh step.
"""
import csv
import datetime
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MECH = "mechanical"
SPEC = f"{MECH}/outputs.yaml"
LEDGER = f"{MECH}/OUTPUTS.csv"
PARAMS = f"{MECH}/cad/generated/params.scad"
KEY_LAYOUT = "config/key-layout.yaml"
BODY = "config/body.yaml"
# Directories whose every file must be an output this tool owns. A PNG that
# nobody can regenerate is exactly the artefact this tool exists to prevent.
OWNED_DIRS = [f"{MECH}/renders", f"{MECH}/export", f"{MECH}/cad/vendor"]
OWNED_EXT = (".png", ".dxf", ".svg", ".stl", ".echo")

# Bump when the way an output is MADE changes (stamp layout, mesh settings,
# render flags) - it is part of every fingerprint, so a bump marks every
# output stale, which is the truth.
RECIPE = "4"

LEDGER_COLS = ["name", "kind", "out", "fingerprint", "out_sha256", "provisional",
               "built", "tool", "inputs"]


def rel(p):
    return os.path.relpath(os.path.abspath(p), ROOT).replace(os.sep, "/")


def blob_id(path):
    """git's own blob id, so `git log --find-object=<id>` finds the commit."""
    data = open(os.path.join(ROOT, path), "rb").read()
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def sha256(path):
    return hashlib.sha256(open(os.path.join(ROOT, path), "rb").read()).hexdigest()


# ---------------------------------------------------------------- params ----

def scad_value(v):
    if v is None:
        return "undef"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(scad_value(x) for x in v) + "]"
    raise TypeError(f"cannot express {v!r} in OpenSCAD")


def scad_name(key):
    return re.sub(r"[^A-Za-z0-9_]", "_", key)


def flatten(prefix, node, out):
    """body.yaml nests groups; each leaf carrying `value` becomes one variable."""
    for k, v in node.items():
        name = f"{prefix}_{scad_name(k)}" if prefix else scad_name(k)
        if isinstance(v, dict) and "value" in v:
            out.append((name, v))
        elif isinstance(v, dict):
            flatten(name, v, out)


def render_params():
    kl = yaml.safe_load(open(os.path.join(ROOT, KEY_LAYOUT), encoding="utf-8"))
    body = yaml.safe_load(open(os.path.join(ROOT, BODY), encoding="utf-8"))
    L = ["// GENERATED by tools/cad.py params - DO NOT EDIT.",
         f"// Sources: {KEY_LAYOUT}, {BODY}. Edit those, then run",
         "// `python3 tools/cad.py build`; `check` fails on a hand edit here.",
         "// Units: mm. Every value below cites its source in the YAML it came from.",
         ""]

    m = kl["meta"]
    L.append(f"// ---- {KEY_LAYOUT} :: meta")
    for k in ("length", "width", "thickness"):
        L.append(f"envelope_{k} = {scad_value(m['envelope'][k])};")
    L.append(f"plate_cutout = {scad_value(m['plate_cutout'])};")
    L.append(f"plate_thickness = {scad_value(m['plate_thickness'])};  // `plate-thickness`, config/figures.yaml")
    L.append("")

    L.append(f"// ---- {KEY_LAYOUT} :: keys")
    L.append("// [id, face, x, y, rotation, hand, cluster, role]; x/y undef = not yet placed (M2/M3)")
    rows = []
    for k in kl["keys"]:
        rows.append("  " + scad_value([k["id"], k["face"], k["x"], k["y"],
                                        k.get("rotation", 0), k["hand"],
                                        k["cluster"], k["role"]]))
    L.append("keys = [\n" + ",\n".join(rows) + "\n];")
    placed = sum(1 for k in kl["keys"] if k["x"] is not None and k["y"] is not None)
    L.append(f"keys_placed = {placed};  // of {len(kl['keys'])}")
    L.append(f"spare_switch_cutouts = {scad_value(kl.get('spare_bits_switches', 0))};")
    L.append("")

    leaves = []
    flatten("", {k: v for k, v in body.items() if k != "meta"}, leaves)
    L.append(f"// ---- {BODY}")
    for name, spec in leaves:
        tag = spec.get("status", "")
        src = spec.get("source", "")
        L.append(f"{name} = {scad_value(spec['value'])};  // {tag}; {src}".rstrip("; "))
    L.append("")
    L.append("// Every value above with status tbd - a placeholder, not a number any")
    L.append("// document gives. The DRC report lists these so no result hides one.")
    L.append("tbd_params = " + scad_value([n for n, s in leaves if s.get("status") == "tbd"]) + ";")
    L.append("")
    return "\n".join(L) + "\n"


def is_provisional():
    kl = yaml.safe_load(open(os.path.join(ROOT, KEY_LAYOUT), encoding="utf-8"))
    return any(k["x"] is None or k["y"] is None for k in kl["keys"])


def params_problems():
    want = render_params()
    path = os.path.join(ROOT, PARAMS)
    if not os.path.exists(path):
        return [f"{PARAMS} is missing - run `python3 tools/cad.py build`"]
    if open(path, encoding="utf-8").read() != want:
        return [f"{PARAMS} does not match {KEY_LAYOUT} + {BODY} - either a config "
                f"value moved (run `python3 tools/cad.py build`, which also re-renders "
                f"what it feeds) or the file was edited by hand (edit the YAML instead)"]
    return []


def write_params():
    os.makedirs(os.path.dirname(os.path.join(ROOT, PARAMS)), exist_ok=True)
    with open(os.path.join(ROOT, PARAMS), "w", encoding="utf-8", newline="\n") as f:
        f.write(render_params())


# ------------------------------------------------------------ dependencies --

INCLUDE_RE = re.compile(r"\b(?:include|use)\s*<([^>]+)>")
# Any string literal naming a data file counts, not just import("..."):
# the model imports through variables (DISP_DXF = "..."), and a walk that
# only read call sites missed one on its first run - caught by the depfile
# cross-check in check_depfile(), which is why that check exists.
IMPORT_RE = re.compile(r"\"([^\"]+\.(?:stl|dxf|svg|off|amf|3mf|png|dat|csv|json))\"", re.I)


def strip_comments(src):
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    return re.sub(r"//[^\n]*", "", src)


def scad_deps(path, seen=None):
    """Every file an OpenSCAD source reads, transitively. Relative paths only:
    a dependency on the OpenSCAD library path would be invisible to git and
    so to the fingerprint, and is refused rather than silently skipped."""
    seen = set() if seen is None else seen
    if path in seen:
        return seen
    full = os.path.join(ROOT, path)
    if not os.path.exists(full):
        raise SystemExit(f"cad.py: {path} does not exist (named as a dependency)")
    seen.add(path)
    if not path.endswith(".scad"):
        return seen
    src = strip_comments(open(full, encoding="utf-8").read())
    base = os.path.dirname(path)
    for m in INCLUDE_RE.finditer(src):
        scad_deps(rel(os.path.join(ROOT, base, m.group(1))), seen)
    for m in IMPORT_RE.finditer(src):
        scad_deps(rel(os.path.join(ROOT, base, m.group(1))), seen)
    return seen


def output_inputs(o):
    if o["kind"] == "mesh":
        deps = {o["from"]}
    else:
        deps = scad_deps(o["src"])
    return sorted(deps)


def fingerprint(o, inputs):
    recipe = {k: v for k, v in o.items() if k not in ("title", "caption")}
    h = hashlib.sha256()
    h.update(json.dumps({"recipe": RECIPE, "spec": recipe}, sort_keys=True).encode())
    for p in inputs:
        h.update(f"{p}\0{blob_id(p)}\n".encode())
    return h.hexdigest()[:16]


# ------------------------------------------------------------------ spec ----

def load_spec():
    spec = yaml.safe_load(open(os.path.join(ROOT, SPEC), encoding="utf-8"))
    outs = []
    for kind, key in (("mesh", "meshes"), ("render", "renders"), ("export", "exports")):
        for o in spec.get(key) or []:
            o = dict(o)
            o["kind"] = kind
            outs.append(o)
    names = [o["name"] for o in outs]
    dup = {n for n in names if names.count(n) > 1}
    if dup:
        raise SystemExit(f"cad.py: duplicate output names in {SPEC}: {sorted(dup)}")
    return outs


def load_ledger():
    path = os.path.join(ROOT, LEDGER)
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8", newline="") as f:
        return {r["name"]: r for r in csv.DictReader(f)}


def write_ledger(rows):
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=LEDGER_COLS, lineterminator="\n")
    w.writeheader()
    for name in sorted(rows):
        w.writerow(rows[name])
    open(os.path.join(ROOT, LEDGER), "w", encoding="utf-8", newline="").write(buf.getvalue())


def encode_inputs(inputs):
    return ";".join(f"{p}@{blob_id(p)[:12]}" for p in inputs)


def decode_inputs(s):
    return dict(x.rsplit("@", 1) for x in s.split(";") if x)


# ----------------------------------------------------------------- build ----

def openscad_version():
    r = subprocess.run(["openscad", "--version"], capture_output=True, text=True)
    return (r.stdout + r.stderr).strip().splitlines()[-1]


def defines(o):
    args = []
    for k, v in (o.get("defines") or {}).items():
        args += ["-D", f"{k}={scad_value(v)}"]
    return args


def run_openscad(o, out_abs, deps_abs):
    cmd = ["openscad", "-o", out_abs, "-d", deps_abs]
    if o["kind"] == "render":
        w, h = o.get("imgsize", [1400, 800])
        cmd += ["--preview", f"--colorscheme={o.get('colorscheme', 'Tomorrow')}",
                f"--imgsize={w},{h}",
                f"--projection={'o' if o.get('projection', 'p') == 'o' else 'p'}"]
        if "camera" in o:
            cmd.append("--camera=" + ",".join(str(c) for c in o["camera"]))
        if o.get("viewall", "camera" not in o):
            cmd += ["--viewall", "--autocenter"]
    cmd += defines(o) + [os.path.join(ROOT, o["src"])]
    if o["kind"] == "render" and not os.environ.get("DISPLAY"):
        cmd = ["xvfb-run", "-a", "-s", "-screen 0 2400x1600x24"] + cmd
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    log = r.stdout + r.stderr
    bad = [l for l in log.splitlines()
           if re.search(r"\b(ERROR|WARNING)\b", l) and "fontconfig" not in l.lower()
           # A banked vendor DXF carries annotation entities (hatches, text)
           # OpenSCAD cannot read. The outline it can read is what is used, and
           # only files under datasheets/ get this pass - never our own.
           and not re.search(r"Unsupported DXF Entity .* datasheets/", l)]
    if r.returncode != 0 or bad or not os.path.exists(out_abs):
        raise SystemExit(f"cad.py: openscad failed on {o['name']}:\n" + "\n".join(bad or log.splitlines()[-15:]))
    return log


def check_depfile(o, deps_abs, inputs):
    """Cross-check the static walk against what OpenSCAD actually opened. If
    OpenSCAD read a file the walk missed, the fingerprint is blind to it."""
    txt = open(deps_abs, encoding="utf-8").read().replace("\\\n", " ")
    listed = txt.split(":", 1)[1].split() if ":" in txt else []
    seen = {rel(p if os.path.isabs(p) else os.path.join(ROOT, p)) for p in listed}
    missed = sorted(p for p in seen if p not in inputs and not p.startswith(".."))
    if missed:
        raise SystemExit(f"cad.py: OpenSCAD read {missed} for {o['name']} but the "
                         f"dependency walk did not find them - fix scad_deps() before "
                         f"trusting any fingerprint")


def stamp(png, o, fp, provisional):
    from PIL import Image, ImageDraw, ImageFont
    img = Image.open(png).convert("RGB")
    band = 34 if provisional else 22
    out = Image.new("RGB", (img.width, img.height + band), (250, 250, 250))
    out.paste(img, (0, 0))
    d = ImageDraw.Draw(out)
    mono = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
    bold = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    f = ImageFont.truetype(mono, 12) if os.path.exists(mono) else ImageFont.load_default()
    fb = ImageFont.truetype(bold, 11) if os.path.exists(bold) else f
    y0 = img.height
    d.line([(0, y0), (img.width, y0)], fill=(180, 180, 180))
    text = (f"Woody body · {o['name']} · cad {fp[:12]} · {o['src']}"
            f" · verify: python3 tools/cad.py explain {o['name']}")
    d.text((8, y0 + 4), text, fill=(60, 60, 60), font=f)
    if provisional:
        d.text((8, y0 + 19), "PROVISIONAL LAYOUT - key positions are null in "
               "config/key-layout.yaml; keys are placed on the ADR 0009 length "
               "budget until M2/M3", fill=(170, 40, 20), font=fb)
    # Deterministic PNG: no timestamps, no text chunks.
    out.save(png, optimize=True)


def mesh_step(o, out_abs):
    try:
        import gmsh
    except Exception as e:
        raise SystemExit(f"cad.py: gmsh is needed to mesh {o['from']} ({e}). "
                         f"`pip install gmsh` (and apt `libxft2 libglu1-mesa`).")
    gmsh.initialize()
    gmsh.option.setNumber("General.Terminal", 0)
    gmsh.option.setNumber("Mesh.MeshSizeFactor", o.get("mesh_size_factor", 0.5))
    gmsh.option.setNumber("Mesh.Binary", 1)
    occ = gmsh.model.occ
    vols = occ.importShapes(os.path.join(ROOT, o["from"]))
    # Vendor STEPs arrive as several touching bodies. Unfused, their meshes
    # overlap and OpenSCAD's CSG preview garbles any section through them;
    # fused, they are one closed solid. `clip` trims what the vendor models
    # but the instrument does not have (the display's unfolded flex).
    if o.get("fuse", True) and len(vols) > 1:
        vols, _ = occ.fuse(vols[:1], vols[1:])
    if "clip" in o:
        c = o["clip"]
        box = occ.addBox(c[0], c[1], c[2], c[3] - c[0], c[4] - c[1], c[5] - c[2])
        vols, _ = occ.intersect(vols, [(3, box)])
    occ.synchronize()
    gmsh.model.mesh.generate(2)
    gmsh.write(out_abs)
    gmsh.finalize()
    return f"gmsh {gmsh.__version__}"


def build_one(o, provisional):
    inputs = output_inputs(o)
    fp = fingerprint(o, inputs)
    out_abs = os.path.join(ROOT, o["out"])
    os.makedirs(os.path.dirname(out_abs), exist_ok=True)
    if o["kind"] == "mesh":
        tool = mesh_step(o, out_abs)
    else:
        with tempfile.TemporaryDirectory() as td:
            deps_abs = os.path.join(td, "deps")
            run_openscad(o, out_abs, deps_abs)
            check_depfile(o, deps_abs, inputs)
        tool = openscad_version()
        if o["kind"] == "render":
            stamp(out_abs, o, fp, provisional and o.get("layout_sensitive", True))
    return {"name": o["name"], "kind": o["kind"], "out": o["out"], "fingerprint": fp,
            "out_sha256": sha256(o["out"])[:16],
            "provisional": "yes" if provisional and o["kind"] != "mesh" else "",
            "built": datetime.date.today().isoformat(), "tool": tool,
            "inputs": encode_inputs(inputs)}


def order(outs):
    # Meshes first: renders import them, so their fingerprints depend on them.
    return sorted(outs, key=lambda o: {"mesh": 0, "export": 1, "render": 2}[o["kind"]])


def cmd_build(names, all_):
    write_params()
    outs = order(load_spec())
    known = {o["name"] for o in outs}
    unknown = [n for n in names if n not in known]
    if unknown:
        raise SystemExit(f"cad.py: no such output(s): {unknown}")
    ledger = load_ledger()
    provisional = is_provisional()
    built = 0
    for o in outs:
        if names and o["name"] not in names:
            continue
        if not names and not all_ and not problems_for(o, ledger.get(o["name"])):
            continue
        print(f"  {o['kind']:6} {o['name']:28} -> {o['out']}", flush=True)
        ledger[o["name"]] = build_one(o, provisional)
        write_ledger(ledger)
        built += 1
    stale_rows = [n for n in ledger if n not in known]
    for n in stale_rows:
        del ledger[n]
    write_ledger(ledger)
    print(f"built {built} of {len(outs)} outputs"
          + (f", dropped {len(stale_rows)} ledger rows with no spec" if stale_rows else ""))
    rest = all_problems()
    if rest:
        print("\n".join("  " + p for p in rest))
        return 1
    return 0


# ----------------------------------------------------------------- check ----

def problems_for(o, row):
    if row is None:
        return [f"{o['name']}: never built - no row in {LEDGER}"]
    if not os.path.exists(os.path.join(ROOT, o["out"])):
        return [f"{o['name']}: {o['out']} is missing"]
    if row["out"] != o["out"]:
        return [f"{o['name']}: ledger says {row['out']}, spec says {o['out']}"]
    if sha256(o["out"])[:16] != row["out_sha256"]:
        return [f"{o['name']}: {o['out']} was changed after it was built - it is no "
                f"longer the file the ledger vouches for. Rebuild it; never edit an output"]
    inputs = output_inputs(o)
    if fingerprint(o, inputs) == row["fingerprint"]:
        return []
    was = decode_inputs(row["inputs"])
    now = {p: blob_id(p)[:12] for p in inputs}
    moved = [p for p in now if p in was and was[p] != now[p]]
    added = [p for p in now if p not in was]
    gone = [p for p in was if p not in now]
    why = ([f"changed {', '.join(moved)}"] if moved else []) + \
          ([f"new input {', '.join(added)}"] if added else []) + \
          ([f"dropped input {', '.join(gone)}"] if gone else [])
    return [f"{o['name']}: STALE - {'; '.join(why) or 'its recipe in outputs.yaml changed'}"]


def all_problems():
    out = params_problems()
    outs = load_spec()
    if out:
        fed = [o["name"] for o in outs if o["kind"] != "mesh" and PARAMS in output_inputs(o)]
        out.append(f"...and {len(fed)} outputs are built from {PARAMS}, so every one of "
                   f"them shows the OLD value until the build runs: {', '.join(fed)}")
    ledger = load_ledger()
    for o in outs:
        out += problems_for(o, ledger.get(o["name"]))
    owned = {o["out"] for o in outs}
    for n in ledger:
        if n not in {o["name"] for o in outs}:
            out.append(f"{n}: in {LEDGER} but not in {SPEC}")
    for d in OWNED_DIRS:
        for dp, _, fs in os.walk(os.path.join(ROOT, d)):
            for fn in fs:
                p = rel(os.path.join(dp, fn))
                if fn.endswith(OWNED_EXT) and p not in owned:
                    out.append(f"{p}: an output no spec entry builds - nobody can "
                               f"regenerate it, so nobody can tell when it goes stale")
    # Every image a mechanical page shows must be one this tool vouches for.
    for dp, _, fs in os.walk(os.path.join(ROOT, MECH)):
        for fn in fs:
            if not fn.endswith(".md"):
                continue
            page = rel(os.path.join(dp, fn))
            for m in re.finditer(r"!\[[^\]]*\]\(([^)\s]+)\)", open(os.path.join(dp, fn), encoding="utf-8").read()):
                tgt = rel(os.path.join(dp, m.group(1)))
                if tgt not in owned:
                    out.append(f"{page} shows {m.group(1)}, which is not a tracked output")
    return out


def cmd_check():
    probs = all_problems()
    n = len(load_spec())
    if probs:
        for p in probs:
            print("  " + p)
        print(f"FAIL {len(probs)} CAD output problem(s) of {n} outputs - "
              f"run `python3 tools/cad.py build`")
        return 1
    print(f"PASS {n} CAD outputs match their sources")
    return 0


def git(*a):
    r = subprocess.run(["git", *a], capture_output=True, text=True, cwd=ROOT)
    return r.stdout.strip()


def cmd_explain(names):
    outs = {o["name"]: o for o in load_spec()}
    ledger = load_ledger()
    for n in names or sorted(outs):
        o, row = outs.get(n), ledger.get(n)
        if o is None:
            print(f"{n}: no such output")
            continue
        print(f"{n}  ({o['kind']}, {o['out']})")
        if row is None:
            print("  never built")
            continue
        print(f"  built {row['built']} with {row['tool']}; stamp cad {row['fingerprint'][:12]}")
        was = decode_inputs(row["inputs"])
        now = {p: blob_id(p)[:12] for p in output_inputs(o)}
        for p in sorted(set(was) | set(now)):
            a, b = was.get(p), now.get(p)
            # Full blob ids are needed for --find-object; recover from history.
            when = ""
            if a:
                full = git("rev-parse", "--verify", "--quiet", f"{a}^{{blob}}") or ""
                if full:
                    when = git("log", "-1", "--format=%h %ad", "--date=short",
                               f"--find-object={full}", "--", p)
            state = "same" if a == b else ("NEW" if not a else "GONE" if not b else "MOVED")
            print(f"  {state:5} {p}  built@{a or '-'}  now@{b or '-'}"
                  + (f"  (built from commit {when})" if when else ""))
        print("  " + ("; ".join(problems_for(o, row)) or "fresh"))


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    cmd, rest = argv[0], argv[1:]
    if cmd == "params":
        write_params()
        print(f"wrote {PARAMS}")
        return 0
    if cmd == "build":
        all_ = "--all" in rest
        return cmd_build([r for r in rest if r != "--all"], all_)
    if cmd == "check":
        return cmd_check()
    if cmd == "explain":
        cmd_explain(rest)
        return 0
    print(f"cad.py: unknown command {cmd!r}\n{__doc__}")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
